#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 24 15:29:52 2026

@author: preciouslawal
"""
def convert_date(input_date):
    '''Convert a given date from a 14/04/2026 format string to a 14 APR 2026 format string'''
    
    month = {
        1:'jan', 2:'feb', 3:'mar', 4:'apr', 5:'may', 6:'jun', 
        7:'jul', 8:'aug', 9:'sep', 10:'oct', 11:'nov', 12:'dec'
}
    
 # easter egg message
    if input_date == "19/01/2038":
            return "The Epochalypse has arrived"
# Split the date string into separate parts (day, month and year)
    parts = input_date.split( "/")

    day = parts[0]
    month_number = int(parts[1])
    year = parts[2]
# To convert the abbreviation ‘apr’ into uppercase
# Look at the dict using the int month_number
    month_number = month[month_number].upper()
    return f"{day} {month_number} {year}"
assert convert_date("14/04/2026") == "14 APR 2026"
assert convert_date("19/01/2038") == "The Epochalypse has arrived"
print(convert_date("14/04/2026"))
print(convert_date("19/01/2038"))

print("You got the dates right!")


    
